//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotProgram.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BotProgram.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Level xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;BoardWidth&gt;50&lt;/BoardWidth&gt;
        ///  &lt;BoardHeight&gt;50&lt;/BoardHeight&gt;
        ///  &lt;Walls&gt;
        ///    &lt;Wall&gt;
        ///      &lt;XPos&gt;15&lt;/XPos&gt;
        ///      &lt;YPos&gt;0&lt;/YPos&gt;
        ///      &lt;Horizontal&gt;false&lt;/Horizontal&gt;
        ///    &lt;/Wall&gt;
        ///    &lt;Wall&gt;
        ///      &lt;XPos&gt;16&lt;/XPos&gt;
        ///      &lt;YPos&gt;20&lt;/YPos&gt;
        ///      &lt;Horizontal&gt;true&lt;/Horizontal&gt;
        ///    &lt;/Wall&gt;
        ///  &lt;/Walls&gt;
        ///  &lt;Exit&gt;
        ///    &lt;XPos&gt;48&lt;/XPos&gt;
        ///    &lt;YPos&gt;3&lt;/YPos&gt;
        ///  &lt;/Exit&gt;
        ///  &lt;Gates&gt;
        ///    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level_1 {
            get {
                return ResourceManager.GetString("level_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Level xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;BoardWidth&gt;70&lt;/BoardWidth&gt;
        ///  &lt;BoardHeight&gt;30&lt;/BoardHeight&gt;
        ///  &lt;Walls&gt;
        ///    &lt;Wall&gt;
        ///      &lt;XPos&gt;15&lt;/XPos&gt;
        ///      &lt;YPos&gt;0&lt;/YPos&gt;
        ///      &lt;Horizontal&gt;false&lt;/Horizontal&gt;
        ///    &lt;/Wall&gt;
        ///    &lt;Wall&gt;
        ///      &lt;XPos&gt;30&lt;/XPos&gt;
        ///      &lt;YPos&gt;0&lt;/YPos&gt;
        ///      &lt;Horizontal&gt;false&lt;/Horizontal&gt;
        ///    &lt;/Wall&gt;
        ///    &lt;Wall&gt;
        ///      &lt;XPos&gt;17&lt;/XPos&gt;
        ///      &lt;YPos&gt;15&lt;/YPos&gt;
        ///      &lt;Horizontal&gt;true&lt;/Horizont [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level_2 {
            get {
                return ResourceManager.GetString("level_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;note&gt;
        ///&lt;to&gt;Tove&lt;/to&gt;
        ///&lt;from&gt;Jani&lt;/from&gt;
        ///&lt;heading&gt;Reminder&lt;/heading&gt;
        ///&lt;body&gt;Don&apos;t forget me this weekend!&lt;/body&gt;
        ///&lt;/note&gt;.
        /// </summary>
        internal static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }
    }
}
